import { StyleSheet, Text, View } from 'react-native';
import { AppHeader } from '@/src/components/AppHeader';
import { Screen } from '@/src/components/Screen';
import { colors, radius } from '@/src/theme/tokens';

export default function HealthReportScreen() {
  return <Screen scroll><AppHeader title="AI 건강 리포트" back /><View style={styles.body}><View style={styles.summary}><Text style={styles.kicker}>이번 주 웰니스 요약</Text><Text style={styles.score}>74</Text><Text style={styles.unit}>/ 100</Text><Text style={styles.summaryCopy}>수면은 안정적이었지만 수분 섭취와 스트레스 관리가 필요해요.</Text></View><Text style={styles.heading}>생활 패턴</Text>{[['수면', '평균 6시간 20분', 0.72], ['컨디션', '보통 이상 4일', 0.64], ['실천한 제안', '5개 중 3개', 0.6]].map(([label, value, ratio]) => <View style={styles.metric} key={String(label)}><View style={styles.metricTop}><Text style={styles.metricLabel}>{label}</Text><Text style={styles.metricValue}>{value}</Text></View><View style={styles.track}><View style={[styles.fill, { width: `${Number(ratio) * 100}%` }]} /></View></View>)}<View style={styles.insight}><Text style={styles.insightTitle}>AI 한 줄 인사이트</Text><Text style={styles.insightCopy}>늦게 잠든 다음 날 피부 불편 기록이 반복됐어요. 이번 주에는 취침 시간을 20분만 앞당겨보세요.</Text></View></View></Screen>;
}

const styles = StyleSheet.create({ body: { paddingHorizontal: 24, paddingTop: 20, paddingBottom: 60 }, summary: { minHeight: 230, borderRadius: radius.lg, backgroundColor: colors.warningSoft, padding: 24 }, kicker: { fontSize: 14, color: colors.muted }, score: { fontSize: 64, fontWeight: '800', marginTop: 14 }, unit: { position: 'absolute', left: 102, top: 85, color: colors.muted }, summaryCopy: { fontSize: 14, lineHeight: 22, marginTop: 12 }, heading: { fontSize: 18, fontWeight: '800', marginTop: 34, marginBottom: 8 }, metric: { paddingVertical: 18 }, metricTop: { flexDirection: 'row', justifyContent: 'space-between' }, metricLabel: { fontSize: 15, fontWeight: '700' }, metricValue: { fontSize: 13, color: colors.muted }, track: { height: 8, borderRadius: 4, backgroundColor: colors.surfaceStrong, marginTop: 12 }, fill: { height: 8, borderRadius: 4, backgroundColor: colors.accent }, insight: { marginTop: 22, borderRadius: radius.md, padding: 20, backgroundColor: colors.surface }, insightTitle: { fontSize: 15, fontWeight: '800' }, insightCopy: { fontSize: 13, lineHeight: 21, color: colors.muted, marginTop: 10 } });
